Authentication Flow
├── Sign-in
├── Register-options
│   ├── Register as professional
│   └── Register as client
├── Register
├── Request try-out account (website)
├── Accept invitation for care plan
└── Forgot password

Sidebar Navigation
├── Dashboard
├── Widget: working on
├── Widget: Monitor
├── Widget: Therapieland video
├── Widget: Therapieland overview
├── Widget: Coaching
├── Help avatar
├── Button Action: program overview (only for non-blended clients)
└── Programs (only for non-blended clients)
    ├── Tab: care plan [name]
    └── Button Action: add program

Topbar Navigation
├── Monitors
│   ├── Button Action: add new monitor
│   └── Active monitor
├── Care plan
│   ├── Button Action: add
│   ├── Care plan [name]
│   ├── Assigned programs and / or questionnaires
│   ├── Access
│   ├── Button Action: invite prof
│   └── Assigned program or questionnaire (Treatment assignment)
│       ├── Button Action: start/continue program
│       ├── Tab: introduction
│       ├── Tab: progress
│       ├── Button Action: invite to care plan
│       ├── Button Action: show access management
│       ├── Program step (Treatment-assignment-step)
│       └── Tab: library
│           └── Questionnaire (questionnaire-assignment)
└── Coaching (only when available)

Help Section
├── User guide for professionals
├── User guide for clients
├── Treatments
├── Care plan
├── Login
├── General
├── Questionnaires
├── Video calling
└── Chat